docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker-compose --env-file ./sample.env --verbose build
