--
-- PostgreSQL database dump
--

-- Dumped from database version 11.9 (Debian 11.9-0+deb10u1)
-- Dumped by pg_dump version 11.9 (Debian 11.9-0+deb10u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: exploit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exploit (
    exploit_id integer NOT NULL,
    cve_number character varying(255) NOT NULL,
    base_score character varying(255) NOT NULL,
    reference_source character varying(255) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.exploit OWNER TO postgres;

--
-- Name: exploit_exploit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.exploit_exploit_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.exploit_exploit_id_seq OWNER TO postgres;

--
-- Name: exploit_exploit_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.exploit_exploit_id_seq OWNED BY public.exploit.exploit_id;


--
-- Name: host; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.host (
    mac character varying(255) NOT NULL,
    netaddr character varying(255) NOT NULL,
    ip character varying(255),
    hostname character varying(255),
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    vendor character varying,
    last_scanned timestamp with time zone DEFAULT now()
);


ALTER TABLE public.host OWNER TO postgres;

--
-- Name: hostservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hostservice (
    mac character varying(255) NOT NULL,
    service_id integer NOT NULL
);


ALTER TABLE public.hostservice OWNER TO postgres;

--
-- Name: interface; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interface (
    interface character varying NOT NULL,
    mac character varying NOT NULL
);


ALTER TABLE public.interface OWNER TO postgres;

--
-- Name: network; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.network (
    netaddr character varying(255) NOT NULL,
    interface_name character varying(255),
    network character varying(255),
    netmask character varying(255)
);


ALTER TABLE public.network OWNER TO postgres;

--
-- Name: service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service (
    service_id integer NOT NULL,
    version character varying(255),
    cpe character varying(255),
    product character varying(255),
    port integer,
    protocol character varying(255)
);


ALTER TABLE public.service OWNER TO postgres;

--
-- Name: service_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service ALTER COLUMN service_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: serviceexploit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.serviceexploit (
    service_id integer NOT NULL,
    exploit_id integer NOT NULL
);


ALTER TABLE public.serviceexploit OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    username character varying NOT NULL,
    password character varying NOT NULL,
    date_created timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: exploit exploit_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exploit ALTER COLUMN exploit_id SET DEFAULT nextval('public.exploit_exploit_id_seq'::regclass);


--
-- Name: exploit pk_exploit; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exploit
    ADD CONSTRAINT pk_exploit PRIMARY KEY (exploit_id);


--
-- Name: host pk_host; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.host
    ADD CONSTRAINT pk_host PRIMARY KEY (mac);


--
-- Name: hostservice pk_hostservice; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hostservice
    ADD CONSTRAINT pk_hostservice PRIMARY KEY (mac, service_id);


--
-- Name: interface pk_interface; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interface
    ADD CONSTRAINT pk_interface PRIMARY KEY (interface, mac);


--
-- Name: network pk_network; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.network
    ADD CONSTRAINT pk_network PRIMARY KEY (netaddr);


--
-- Name: service pk_service; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT pk_service PRIMARY KEY (service_id);


--
-- Name: serviceexploit pk_serviceexploit; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.serviceexploit
    ADD CONSTRAINT pk_serviceexploit PRIMARY KEY (service_id, exploit_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (username);


--
-- Name: serviceexploit fk_exploit; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.serviceexploit
    ADD CONSTRAINT fk_exploit FOREIGN KEY (exploit_id) REFERENCES public.exploit(exploit_id);


--
-- Name: host fk_host; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.host
    ADD CONSTRAINT fk_host FOREIGN KEY (netaddr) REFERENCES public.network(netaddr);


--
-- Name: hostservice fk_host; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hostservice
    ADD CONSTRAINT fk_host FOREIGN KEY (mac) REFERENCES public.host(mac);


--
-- Name: interface fk_host; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interface
    ADD CONSTRAINT fk_host FOREIGN KEY (mac) REFERENCES public.host(mac);


--
-- Name: hostservice fk_service; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hostservice
    ADD CONSTRAINT fk_service FOREIGN KEY (service_id) REFERENCES public.service(service_id);


--
-- Name: serviceexploit fk_service; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.serviceexploit
    ADD CONSTRAINT fk_service FOREIGN KEY (service_id) REFERENCES public.service(service_id);


--
-- PostgreSQL database dump complete
--

